import q1 from './q1.png'
import q2 from './q2.png'
import q3 from './q3.png'

export const quiz2 ={
    quizId:2,
    quizName:"Numerical Assessment",
    category:"Numerical",
    totalQuestions:14,
    totalTime:"15 mins",
    questions : [
        {
            Sno:1,
            type:"MCQ",
            attachment:q1,
            question:"Which agent has the lowest call resolution?",
            options : ["Agent A","Agent B","Agent C","Agent D"],
            correctAnswer:"Agent D",
            explanation:"Agent D has the lowest call resolution (30%).",
        },
        {
            Sno:2,
            type:"MCQ",
            attachment:q1,
            question:"When a new employee joined, their rating was 3 points lower than the highest score. What was the rating of the new employee?",
            options : ["7","4","8","6"],
            correctAnswer:"6",
            explanation:"Given that the highest score is 9 (corresponding to Employee C), 3 points lower than that would be 6.",
        },
        {
            Sno:3,
            type:"MCQ",
            attachment:q1,
            question:"Find the average call resolution percentage across the 4 agents",
            options : ["59.5%","79.33%","69.33%","47.6%"],
            correctAnswer:"59.5%",
            explanation:"Average call resolution percentage across the 4 agents: Average = (75 + 45 + 88 + 30)/4 = 238/4 = 59.5%",
        },
        {
            Sno:4,
            type:"Floating Type",
            attachment:q1,
            question:"If agent C's average handling time goes up by 5 percent, what would be their new average call handling time? (Answer in mins upto 1 decimal place)",
            correctAnswer:"8.4",
            explanation:"If agent C's average handling time goes up by 5 percent, their new average call handling time would be:New handling time = 8 mins + 8 mins * 5% = 8  mins + 0.4 mins = 8.4 mins",
        },
        {
            Sno:5,
            type:"Floating Type",
            attachment:q2,
            question:"What is the total sales for the first five months?",
            correctAnswer:"610000",
            explanation:"$120K + $95K + $150K + $110K + $135K = $610,000",
        },
        {
            Sno:6,
            type:"Floating Type",
            attachment:q2,
            question:"What is the average sales per month for the given period?",
            correctAnswer:"122000",
            explanation:"Total sales / Number of months = $610,000 / 5 = $122,000",
        },
        {
            Sno:7,
            type:"Floating Type",
            attachment:q2,
            question:"Calculate the percentage increase in sales from February to March.(Round off to nearest Integer)",
            correctAnswer:"58",
            explanation:"Percentage increase from February to March: [(March sales - February sales) / February sales] * 100% [($150K - $95K) / $95K] * 100% = (55 / 95) * 100% ≈ 57.89%",
        },
        {
            Sno:8,
            type:"MCQ",
            attachment:q2,
            question:"Identify the month with the highest sales and the month with the lowest sales.",
            options : ["March & Feburary","January & Feburary","April & May","March & May"],
            correctAnswer:"March & Feburary",
            explanation:"Highest sales month: March with $150,000 & Lowest sales month: February with $95,000",
        },
        {
            Sno:9,
            type:"Floating Type",
            attachment:q2,
            question:"Compare the total sales in April and May. How much higher or lower are the sales in May compared to April?",
            correctAnswer:"25000",
            explanation:"Difference in sales between April and May:May sales - April sales = $135,000 - $110,000 = $25,000 .The sales in May are $25,000 higher than April",
        },
        {
            Sno:10,
            type:"Floating Type",
            attachment:q3,
            question:"If the trip with an arrival time of 08:00 AM and a departure time of 12:00 PM included an unexpected delay of 45 minutes, at what time did the trip actually depart?",
            correctAnswer:"1245",
            explanation:"Actual departure time = Departure time + Delay. Actual departure time = 12:00 PM + 45 minutes = 12:45 PM. The trip actually departed at 12:45 PM due to the delay. ",
        },
        {
            Sno:11,
            type:"Floating Type",
            attachment:q3,
            question:"If the cost per person for the trip with an arrival time of 09:30 AM and a departure time of 02:00 PM increased by 15%, what would be the new cost per person?",
            correctAnswer:"74.75",
            explanation:"Original cost per person = $65.Increase in cost = Original cost * 15% = $65 * 0.15 = $9.75.New cost per person = Original cost + Increase in cost = $65 + $9.75 = $74.75. The new cost per person would be approximately $74.75 after a 15% increase.",
        },
        {
            Sno:12,
            type:"MCQ",
            attachment:q3,
            question:"Compare the average number of stops for trips that have an arrival time before 11:00 AM to those that have an arrival time after 11:00 AM. Which set of trips has a higher average number of stops?",
            options : ["Trips after 11:00 AM","Trips before 11:00 AM"],
            correctAnswer:"Trips after 11:00 AM",
            explanation:"Original cost per person = $65.Increase in cost = Original cost * 15% = $65 * 0.15 = $9.75.New cost per person = Original cost + Increase in cost = $65 + $9.75 = $74.75. The new cost per person would be approximately $74.75 after a 15% increase.",
        },
        {
            Sno:13,
            type:"Floating Type",
            attachment:q3,
            question:"If the total revenue generated from a trip with an arrival time of 10:45 AM and a departure time of 03:30 PM was $1750, what was the average cost per person for this trip?",
            correctAnswer:"350",
            explanation:"Total revenue = Total number of people * Cost per person. Cost per person = Total revenue / Total number of people. Cost per person = $1750 / 5 = $350",
        },
        {
            Sno:14,
            type:"MCQ",
            attachment:q3,
            question:"The trip with an arrival time of 12:30 PM and a departure time of 06:30 PM experienced an unexpected delay of 30 minutes at one of the stops. What was the total duration of the trip after considering this delay?",
            options:["6 hours 40 mins","7 hours 30 mins","6 hours 30 mins","12 hours 40 mins"],
            correctAnswer:"6 hours 30 mins",
            explanation:"Original duration = Departure time - Arrival time = 06:30 PM - 12:30 PM = 6 hours. Total duration with delay = Original duration + Delay = 6 hours + 30 minutes = 6 hours 30 minutes. The total duration of the trip, including the 30-minute delay, was 6 hours and 30 minutes.",
        },
    ]
}