export const quiz5 ={
    quizId:5,
    quizName:"Big5",
    category:"Personality",
    totalQuestions:44,
    totalTime:"no limit",
    questions : [
        {
            Sno:1,
            type:"Extraversion",
            question:"I see myself as someone who enjoys talking",
            scoretype:"normal",
        },
        {
            Sno:2,
            type:"Agreeableness",
            question:"I see myself as someone who tends to notice mistakes made by others",
            scoretype:"reverse",
        },
        {
            Sno:3,
            type:"Conscientiousness",
            question:"I see myself as someone who is able to comprehensively complete demands of a task ",
            scoretype:"normal",
        },
        {
            Sno:4,
            type:"Neuroticism",
            question:"I see myself as someone who experiences significantly negative emotions",
            scoretype:"normal",
        },
        {
            Sno:5,
            type:"Openness",
            question:"I see myself as someone who able to come up with new ideas",
            scoretype:"normal",
        },
        {
            Sno:6,
            type:"Extraversion",
            question:"I see myself as someone who tends to maintain some distance from others",
            scoretype:"normal",
        },
        {
            Sno:7,
            type:"Agreeableness",
            question:"I see myself as someone who is helping and aiding others more often than not",
            scoretype:"reverse",
        },
        {
            Sno:8,
            type:"Conscientiousness",
            question:"I see myself as someone who has a tendency to miss out on small details",
            scoretype:"normal",
        },
        {
            Sno:9,
            type:"Neuroticism",
            question:"I see myself as someone who is able to handle stress well",
            scoretype:"reverse",
        },
        {
            Sno:10,
            type:"Openness",
            question:"I see myself as someone who wants to explore many new things",
            scoretype:"normal",
        },
        {
            Sno:11,
            type:"Conscientiousness",
            question:"I see myself as someone who possesses a lot of energy",
            scoretype:"normal",
        },
        {
            Sno:12,
            type:"Agreeableness",
            question:"I see myself as someone who Prefers to confront others more than not",
            scoretype:"reverse",
        },
        {
            Sno:13,
            type:"Conscientiousness",
            question:"I see myself as someone who Is a reliable worker",
            scoretype:"normal",
        },
        {
            Sno:14,
            type:"Neuroticism",
            question:"I see myself as someone who Can be tense",
            scoretype:"normal",
        },
        {
            Sno:15,
            type:"Openness",
            question:"I see myself as someone who Thinks deeply about topics",
            scoretype:"normal",
        },
        {
            Sno:16,
            type:"Extraversion",
            question:"I see myself as someone who Tends to make others more energetic and enthusiastic",
            scoretype:"normal",
        },
        {
            Sno:17,
            type:"Agreeableness",
            question:"I see myself as someone who Remembers other people’s mistakes",
            scoretype:"reverse",
        },
        {
            Sno:18,
            type:"Conscientiousness",
            question:"I see myself as someone who Can be disorganised",
            scoretype:"reverse",
        },
        {
            Sno:19,
            type:"Neuroticism",
            question:"I see myself as someone who Has a tendency to worry",
            scoretype:"normal",
        },
        {
            Sno:20,
            type:"Openness",
            question:"I see myself as someone who Has an active imagination",
            scoretype:"normal",
        },
        {
            Sno:21,
            type:"Extraversion",
            question:"I see myself as someone who Prefers to be quiet",
            scoretype:"reverse",
        },
        {
            Sno:22,
            type:"Agreeableness",
            question:"I see myself as someone who Finds it easy to trust others",
            scoretype:"normal",
        },
        {
            Sno:23,
            type:"Conscientiousness",
            question:"I see myself as someone who Prefers minimal exertion",
            scoretype:"reverse",
        },
        {
            Sno:24,
            type:"Neuroticism",
            question:"I see myself as someone who Does not get easily upset",
            scoretype:"reverse",
        },
        {
            Sno:25,
            type:"Openness",
            question:"I see myself as someone who Comes up with new ideas and applications",
            scoretype:"normal",
        },
        {
            Sno:26,
            type:"Extraversion",
            question:"I see myself as someone who Finds it easy to assert oneself in front of others",
            scoretype:"normal",
        },
        {
            Sno:27,
            type:"Agreeableness",
            question:"I see myself as someone who Is perceived as distant or aloof",
            scoretype:"reverse",
        },
        {
            Sno:28,
            type:"Conscientiousness",
            question:"I see myself as someone who Can continue to work on a task despite many difficulties",
            scoretype:"normal",
        },
        {
            Sno:29,
            type:"Neuroticism",
            question:"I see myself as someone who Is not affected by feelings or emotions",
            scoretype:"reverse",
        },
        {
            Sno:30,
            type:"Openness",
            question:"I see myself as someone who Has a preference for visual aesthetics",
            scoretype:"normal",
        },
        {
            Sno:31,
            type:"Extraversion",
            question:"I see myself as someone who Can be shy sometimes",
            scoretype:"reverse",
        },
        {
            Sno:32,
            type:"Agreeableness",
            question:"I see myself as someone who Finds it easy to consider everyone’s needs around them",
            scoretype:"normal",
        },
        {
            Sno:33,
            type:"Conscientiousness",
            question:"I see myself as someone who Can do tasks rapidly",
            scoretype:"normal",
        },
        {
            Sno:34,
            type:"Neuroticism",
            question:"I see myself as someone who Remains calm in tense situations more often than not",
            scoretype:"reverse",
        },
        {
            Sno:35,
            type:"Openness",
            question:"I see myself as someone who Likes work that is step-by-step over unstructured and free- flowing tasks",
            scoretype:"reverse",
        },
        {
            Sno:36,
            type:"Extraversion",
            question:"I see myself as someone who Likes going out out and interacting with people",
            scoretype:"normal",
        },
        {
            Sno:37,
            type:"Agreeableness",
            question:"I see myself as someone who Finds it hard to filter their thoughts in front of others",
            scoretype:"reverse",
        },
        {
            Sno:38,
            type:"Conscientiousness",
            question:"I see myself as someone who Makes plans and follows through with them",
            scoretype:"normal",
        },
        {
            Sno:39,
            type:"Neuroticism",
            question:"I see myself as someone who Is affected by nerves",
            scoretype:"normal",
        },
        {
            Sno:40,
            type:"Openness",
            question:"I see myself as someone who Likes to think a lot about ideas and play with them",
            scoretype:"normal",
        },
        {
            Sno:41,
            type:"Openness",
            question:"I see myself as someone who Does not enjoy artistic activities",
            scoretype:"reverse",
        },
        {
            Sno:42,
            type:"Agreeableness",
            question:"I see myself as someone who Finds it easy to listen to and go along with others",
            scoretype:"normal",
        },
        {
            Sno:43,
            type:"Conscientiousness",
            question:"I see myself as someone who Tends to get distracted by other things",
            scoretype:"reverse",
        },
        {
            Sno:44,
            type:"Openness",
            question:"I see myself as someone who Has extensive knowledge of art, music or literature",
            scoretype:"normal",
        },
    ]
}